---
title: "R Notebook"
output: html_notebook
---

```{r}
# tidyverse
suppressPackageStartupMessages(library(tidyverse))


# column types
types = cols(
  
  Age = col_double(),
  Attrition = col_factor(),
  BusinessTravel = col_factor(),
  DailyRate = col_double(),
  Department = col_factor(),
  DistanceFromHome = col_double(),
  Education = col_factor(),
  EducationField = col_factor(),
  EmployeeCount = col_skip(),
  EmployeeNumber = col_double(),
  EnvironmentSatisfaction = col_factor(),
  Gender = col_factor(),
  HourlyRate = col_double(),
  JobInvolvement = col_double(),
  JobLevel = col_double(),
  JobRole = col_factor(),
  JobSatisfaction = col_double(),
  MaritalStatus = col_factor(),
  MonthlyIncome = col_double(),
  MonthlyRate = col_double(),
  NumCompaniesWorked = col_double(),
  Over18 = col_skip(),
  OverTime = col_factor(),
  PercentSalaryHike = col_double(),
  PerformanceRating = col_double(),
  RelationshipSatisfaction = col_double(),
  StandardHours = col_skip(),
  StockOptionLevel = col_double(),
  TotalWorkingYears = col_double(),
  TrainingTimesLastYear = col_double(),
  WorkLifeBalance = col_double(),
  YearsAtCompany = col_double(),
  YearsInCurrentRole = col_double(),
  YearsSinceLastPromotion = col_double(),
  YearsWithCurrManager = col_double()
)

# data
ibm = read_csv("data/ibm.csv", col_types = types)
spec(ibm)
```

```{r}
ibm
```

```{r}
# build pairwise graph using numeric columns
png("pairs_ibm.png", width = 2048, height=2048)
pairs(ibm[,c("Age", "DailyRate", "EmployeeNumber", "MonthlyIncome", 
             "NumCompaniesWorked", "PercentSalaryHike", "TotalWorkingYears",
             "TrainingTimesLastYear", "YearsAtCompany", "YearsInCurrentRole", 
             "YearsSinceLastPromotion", "YearsWithCurrManager")])
```


```{r}
pairs(data.frame(ibm$MaritalStatus, ibm$Attrition))
```

